####################################################################################
# Bro log files: https://www.zeek.org/sphinx/script-reference/log-files.html
####################################################################################
name = "bro-domain"
fields = [
  # Common Fields
  "ts",
  "uid",
  "destination_address",
  "destination_port",
  "source_address",
  "source_port"
]

# https://www.zeek.org/sphinx/scripts/base/protocols/conn/main.bro.html#type-Conn::Info
[events.bro_conn]
fields = [
  "conn_proto",
  "conn_service",
  "conn_duration",
  "conn_orig_bytes",
  "conn_resp_bytes",
  "conn_state",
  "conn_local_orig",
  "conn_local_resp",
  "conn_missed_bytes",
  "conn_history",
  "conn_orig_pkts",
  "conn_orig_ip_bytes",
  "conn_resp_pkts",
  "conn_resp_ip_bytes",
  "conn_tunnel_parents",
  "conn_orig_l2_addr",
  "conn_resp_l2_addr",
  "conn_vlan",
  "conn_inner_vlan"
]

# https://www.zeek.org/sphinx/scripts/base/protocols/dns/main.bro.html#type-DNS::Info
[events.bro_dns]
fields = [
  "dns_proto",
  "dns_trans_id",
  "dns_rtt",
  "dns_query",
  "dns_qclass",
  "dns_qclass_name",
  "dns_qtype",
  "dns_qtype_name",
  "dns_rcode",
  "dns_rcode_name",
  "dns_AA",
  "dns_TC",
  "dns_RD",
  "dns_RA",
  "dns_Z",
  "dns_answers",
  "dns_ttl",
  "dns_rejected",
  "dns_total_answers",
  "dns_total_replies",
  "dns_saw_query",
  "dns_saw_reply",
  "dns_auth",
  "dns_addl"
]

# https://www.zeek.org/sphinx/scripts/base/protocols/http/main.bro.html#type-HTTP::Info
[events.bro_http]
fields = [
  "http_trans_depth",
  "http_method",
  "http_host",
  "http_uri",
  "http_referrer",
  "http_version",
  "http_user_agent",
  "http_request_body_len",
  "http_response_body_len",
  "http_status_code",
  "http_status_msg",
  "http_info_code",
  "http_info_msg",
  "http_tags",
  "http_username",
  "http_password",
  "http_capture_password",
  "http_proxied",
  "http_range_request",
  "http_orig_fuids",
  "http_orig_filenames",
  "http_orig_mime_types",
  "http_resp_fuids",
  "http_resp_filenames",
  "http_resp_mime_types",
  "http_current_entity",
  "http_orig_mime_depth",
  "http_resp_mime_depth",
  "http_client_header_names",
  "http_server_header_names",
  "http_omniture",
  "http_flash_version",
  "http_cookie_vars",
  "http_uri_vars",
  "http_mime_type"
]

# https://www.zeek.org/sphinx/scripts/base/protocols/ssl/main.bro.html#type-SSL::Info
[events.bro_ssl]
fields = [
  "ssl_id",
  "ssl_version_num",
  "ssl_version",
  "ssl_cipher",
  "ssl_curve",
  "ssl_server_name",
  "ssl_session_id",
  "ssl_resumed",
  "ssl_client_ticket_empty_session_seen",
  "ssl_client_key_exchange_seen",
  "ssl_server_appdata",
  "ssl_client_appdata",
  "ssl_last_alert",
  "ssl_next_protocol",
  "ssl_analyzer_id",
  "ssl_established",
  "ssl_logged",
  "ssl_delay_tokens"
]

# https://www.zeek.org/sphinx/scripts/base/protocols/rdp/main.bro.html#type-RDP::Info
[events.bro_rdp]
fields = [
  "rdp_id",
  "rdp_cookie",
  "rdp_result",
  "rdp_security_protocol",
  "rdp_keyboard_layout",
  "rdp_client_build",
  "rdp_client_name",
  "rdp_client_dig_product_id",
  "rdp_desktop_width",
  "rdp_desktop_height",
  "rdp_requested_color_depth",
  "rdp_cert_type",
  "rdp_cert_count",
  "rdp_cert_permanent",
  "rdp_encryption_level",
  "rdp_encryption_method",
  "rdp_analyzer_id",
  "rdp_done",
  "rdp_ssl"
]

# https://www.zeek.org/sphinx/scripts/base/frameworks/notice/weird.bro.html#type-Weird::Info
[events.bro_weird]
fields = [
  "weird_id",
  "weird_conn",
  "weird_name",
  "weird_addl",
  "weird_notice",
  "weird_peer",
  "weird_identifier"
]

# https://www.zeek.org/sphinx/scripts/base/files/x509/main.bro.html#type-X509::Info
[events.bro_x509]
fields = [
  "id",
  "x509_certificate",
  "x509_handle",
  "x509_extensions",
  "x509_san",
  "x509_basic_constraints",
  "x509_logcert"
]

# https://www.zeek.org/sphinx/scripts/base/frameworks/files/main.bro.html#type-Files::Info
[events.bro_files]
fields = [
  "files_tx_hosts",
  "files_rx_hosts",
  "files_fuid",
  "files_conn_uids",
  "files_source",
  "files_depth",
  "files_analyzers",
  "files_mime_type",
  "files_filename",
  "files_duration",
  "files_local_orig",
  "files_is_orig",
  "files_seen_bytes",
  "files_missing_bytes",
  "files_overflow_bytes",
  "files_timedout",
  "files_parent_fuid",
  "files_md5",
  "files_sha1",
  "files_sha256",
  "files_x509",
  "files_extracted",  
  "files_extracted_cutoff",
  "files_extracted_size",
  "files_entropy"
]

# https://www.zeek.org/sphinx/scripts/base/protocols/ssh/main.bro.html#type-SSH::Info
[events.bro_ssh]
fields = [
  "ssh_version",
  "ssh_auth_success",
  "ssh_auth_attempts",
  "ssh_direction",
  "ssh_client",
  "ssh_server",
  "ssh_cipher_alg",
  "ssh_mac_alg",
  "ssh_compression_alg",
  "ssh_kex_alg",
  "ssh_host_key_alg",
  "ssh_host_key",
  "ssh_analyzer_id",
  "ssh_remote_location"
]

[events.bro_smb_files]
fields = [
  "smb_action",
  "smb_name",
  "smb_size",
  "smb_times_modified",
  "smb_times_accessed",
  "smb_times_created",
  "smb_times_changed"
]

[events.bro_smb_mapping]
fields = [
  "smb_path",
  "smb_service",
  "smb_share_type"
]