name = "bro-domain"
fields = [
  # Common Fields
  "ts",
  "uid",
  "destination_address"
  #"id.orig_h",
  #"id.orig_p",
  #"id.resp_h",
  #"id.resp_p"
]

[events.bro_conn]
fields = [
  "proto",
  "conn_state",
  "local_orig",
  "local_resp",
  "missed_bytes"
]

[events.bro_dns]
fields = [
  "proto",
  "trans_id",
  "rcode",
  "rcode_name",
  "AA",
  "TC",
  "RD",
  "RA",
  "Z"
]

# [events.conn]
# fields = [
#   "proto",
#   "conn_state",
#   "local_orig",
#   "local_resp",
#   "missed_bytes",
#   "history",
#   "orig_pkts",
#   "orig_ip_bytes",
#   "resp_pkts",
#   "resp_ip_bytes",
#   "tunnel_parents"
# ]


# [events.http]
# fields = [
#   "trans_depth",
#   "version",
#   "request_body_len",
#   "response_body_len",
#   "status_code",
#   "status_msg",
#   "tags",
#   "resp_fuids",
#   "resp_mime_types"
# ]

# name = "Bro events"
# fields = [
#   # Common Fields
#   "ts",
#   "uid",
#   "destination_address",
#   "destination_port",
#   "source_address",
#   "source_port"
# ]

# [events.bro_conn]
# fields = [
#   "proto",
#   "conn_state",
#   "local_orig",
#   "local_resp",
#   "missed_bytes",
#   "history",
#   "orig_pkts",
#   "orig_ip_bytes",
#   "resp_pkts",
#   "resp_ip_bytes",
#   "tunnel_parents"
# ]

# [events.bro_dns]
# fields = [
#   "proto",
#   "trans_id",
#   "rcode",
#   "rcode_name",
#   "AA",
#   "TC",
#   "RD",
#   "RA",
#   "Z",
#   "answers",
#   "TTL",
#   "rejected"
# ]

# [events.bro_ssl]
# fields = [
#   "resumed",
#   "established",
#   "version",
#   "cipher"
# ]

# [events.bro_http]
# fields = [
#   "trans_depth",
#   "method",
#   "host",
#   "uri",
#   "referrer",
#   "version",
#   "user_agent",
#   "request_body_len",
#   "response_body_len",
#   "status_code",
#   "status_msg",
#   "info_msg",
#   "tags",
#   "username",
#   "password",
#   "capture_password",
#   "proxied",
#   "range_request",
#   "orig_fuids",
#   "orig_filenames",
#   "orig_mime_types",
#   "resp_filenames",
#   "current_entity",
#   "orig_mime_depth",
#   "resp_mime_depth",
#   "client_header_names",
#   "server_header_names",
#   "omniture",
#   "flash_version",
#   "cookie_vars",
#   "uri_vars",
#   "resp_fuids",
#   "resp_mime_types"
# ]


# [events.bro_rdp]
# fields = [
#   "id",
#   "cookie",
#   "result",
#   "security_protocol",
#   "keyboard_layout",
#   "client_build",
#   "client_name",
#   "client_dig_product_id",
#   "desktop_width",
#   "desktop_height",
#   "requested_color_depth",
#   "cert_type",
#   "cert_count",
#   "cert_permanent",
#   "encryption_level",
#   "encryption_method",
#   "analyzer_id",
#   "done",
#   "ssl"
# ]

# [events.bro_weird]
# fields = [
#   "name",
#   "notice",
#   "peer"
# ]

# [events.bro_x509]
# fields = [
#   "id",
#   "certificate.version",
#   "certificate.serial",
#   "certificate.subject",
#   "certificate.issuer",
#   "certificate.not_valid_before",
#   "certificate.not_valid_after",
#   "certificate.key_alg",
#   "certificate.sig_alg",
#   "certificate.key_type",
#   "certificate.key_length",
#   "certificate.exponent",
#   "san.dns",
#   "basic_constraints.ca"
# ]

# [events.bro_files]
# fields = [
#   "tx_hosts",
#   "rx_hosts",
#   "fuid",
#   "conn_uids",
#   "source",
#   "depth",
#   "analyzers",
#   "mime_type",
#   "duration",
#   "local_orig",
#   "is_orig",
#   "seen_bytes",
#   "missing_bytes",
#   "overflow_bytes",
#   "timedout",
#   "md5",
#   "sha1",
#   "extracted_cutoff"
# ]

# [events.bro_ssh]
# fields = [
#   "version",
#   "client"
# ]