name = "Bro events"
strict = true
domain = "bro-domain"
filter_query = true

[timestamp]
field = "ts"
# JSON datetime format WITHOUT miliseconds
format = "%Y-%m-%dT%H:%M:%Sz"

[fields.mapping]
ts = "ts"
uid = "uid"
destination_address = 'dest_addr'
destination_port = 'dest_port'
source_address = 'src_addr'
source_port = 'src_port'

#######################################
# Conn
#######################################
[events.bro_conn]
filter = "conn_state"

[events.bro_conn.mapping]
conn_proto = 'proto'
conn_state = 'conn_state'
conn_local_orig = 'local_orig'
conn_local_resp = 'local_resp'

#######################################
# DNS
#######################################
[events.bro_dns]
filter = 'rcode_name'

[events.bro_dns.mapping]
dns_proto = 'proto'
dns_rcode = 'rcode'
dns_rcode_name = 'rcode_name'
dns_query = 'query'
dns_answers = 'answers'
dns_ttl = 'TTLs'

#######################################
# HTTP
#######################################
[events.bro_http]
filter = 'status_code'

[events.bro_http.mapping]
http_version = 'version'
http_method = 'method'
http_host = 'host'
http_uri = 'uri'
http_referrer = 'referrer'
http_user_agent = 'user_agent'
http_status_code = 'status_code'
http_status_msg = 'status_msg'
http_username = 'username'
http_password = 'password'
http_proxied = 'proxied'
http_cookie_vars = 'cookie_vars'
http_uri_vars = 'uri_vars'
http_mime_type = 'resp_mime_types'

#######################################
# SSL
#######################################
[events.bro_ssl]
filter = 'cipher'

[events.bro_ssl.mapping]
ssl_version = 'version'
ssl_cipher = 'cipher'
ssl_curve = 'curve'
ssl_server_name = 'server_name'
ssl_session_id = 'session_id'
ssl_established = 'established'

#######################################
# RDP
#######################################
[events.bro_rdp]
filter = 'keyboard_layout'

[events.bro_rdp.mapping]
rdp_cookie = 'cookie'
rdp_result = 'result'
rdp_security_protocol = 'security_protocol'
rdp_keyboard_layout = 'keyboard_layout'
rdp_client_build = 'client_build'
rdp_client_name = 'client_name'
rdp_cert_type = 'cert_type'
rdp_cert_count = 'cert_count'
rdp_cert_permanent = 'cert_permanent'
rdp_encryption_level = 'encryption_level'
rdp_encryption_method = 'encryption_method'
rdp_ssl = 'ssl'

#######################################
# Weird
#######################################
[events.bro_weird]
filter = 'name'

[events.bro_weird.mapping]
weird_name = 'name'
weird_addl = 'addl'
weird_peer = 'peer'
weird_identifier = 'identifier'

#######################################
# x509
#######################################
[events.bro_x509]
filter = 'certificate.serial'

[events.bro_x509.mapping]
x509_certificate = 'certificate'
x509_extensions = 'extensions'
x509_san = 'san'
x509_basic_constraints = 'basic_constraints'
x509_logcert = 'logcert'

#######################################
# Files
#######################################
[events.bro_files]
filter = 'mime_type'

[events.bro_files.mapping]
files_tx_hosts = 'tx_hosts'
files_rx_hosts = 'rx_hosts'
files_conn_uids = 'conn_uids'
files_source = 'source'
files_mime_type = 'mime_type'
files_filename = 'filename'
files_duration = 'duration'
files_md5 = 'md5'
files_sha1 = 'sha1'
files_sha256 = 'sha256'
files_x509 = 'x509'

#######################################
# SSH
#######################################
[events.bro_ssh]
filter = 'auth_success'

[events.bro_ssh.mapping]
ssh_version = 'version'
ssh_auth_success = 'auth_success'
ssh_auth_attempts = 'auth_attempts'
ssh_direction = 'direction'
ssh_client = 'client'
ssh_server = 'server'
ssh_cipher_alg = 'cipher_alg'
ssh_mac_alg = 'mac_alg'
ssh_compression_alg = 'compression_alg'
ssh_kex_alg = 'kex_alg'
ssh_host_key_alg = 'host_key_alg'
ssh_host_key = 'host_key'